-- require "snippets".use_suggested_mappings(true)
-- vim.cmd(
--     [[
-- 	imap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'
-- 	smap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'
-- ]]
-- )
